import { useEffect, useMemo, useState } from "react";
import {
  aggregatePhosprot,
  createMetadataProfile,
  generateAnnotation,
  getCurrentAnnotation,
  getCurrentDatasets,
  getUploadedAnnotationMetadata,
  renameMetadataProfile,
  setActiveMetadataProfile,
  uploadAnnotationMetadata,
} from "../../lib/api";
import { subscribeDatasetStateChanged } from "../../lib/datasetEvents";
import type {
  AnnotationFilterConfig,
  AnnotationResultResponse,
  ConditionAssignment,
  CurrentDatasetsResponse,
  MetadataUploadResponse,
  MetadataAnnotationKind,
  PhosprotAggregationMode,
} from "../../lib/types";

type ConditionDraft = {
  id: number;
  name: string;
  columns: string[];
};

const DEFAULT_FILTER: AnnotationFilterConfig = {
  minPresent: 0,
  mode: "per_group",
};

export default function AnnotationPage() {
  const [kind, setKind] = useState<MetadataAnnotationKind>("protein");
  const [currentDatasets, setCurrentDatasets] = useState<CurrentDatasetsResponse | null>(
    null
  );
  const [conditions, setConditions] = useState<ConditionDraft[]>([
    { id: 1, name: "", columns: [] },
  ]);
  const [isLog2Transformed, setIsLog2Transformed] = useState(true);
  const [filterConfig, setFilterConfig] = useState<AnnotationFilterConfig>(DEFAULT_FILTER);
  const [result, setResult] = useState<AnnotationResultResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [metadataFile, setMetadataFile] = useState<File | null>(null);
  const [uploadedMetadata, setUploadedMetadata] = useState<MetadataUploadResponse | null>(null);
  const [uploadingMetadata, setUploadingMetadata] = useState(false);
  const [phosprotResult, setPhosprotResult] = useState<AnnotationResultResponse | null>(null);
  const [phosprotMode, setPhosprotMode] =
    useState<PhosprotAggregationMode>("sum_ignore_na");
  const [phosprotBusy, setPhosprotBusy] = useState(false);
  const [metadataProfileBusy, setMetadataProfileBusy] = useState(false);
  const [newMetadataProfileName, setNewMetadataProfileName] = useState("");
  const [renameMetadataProfileName, setRenameMetadataProfileName] = useState("");

  const activeDataset = currentDatasets?.[kind] ?? null;
  const availableColumns = activeDataset?.columnNames ?? [];
  const availableKinds = useMemo<MetadataAnnotationKind[]>(() => {
    const kinds: MetadataAnnotationKind[] = [];
    if (currentDatasets?.protein) kinds.push("protein");
    if (currentDatasets?.phospho) kinds.push("phospho");
    return kinds;
  }, [currentDatasets]);
  const kindOptions = useMemo(
    () =>
      availableKinds.map((value) => ({
        value,
        label: value === "protein" ? "Protein" : "Phospho",
      })),
    [availableKinds]
  );
  const manualMetadataProfiles = useMemo(() => {
    const all = currentDatasets?.availableMetadataProfiles ?? ["Metadata"];
    const auto = new Set(currentDatasets?.autoGeneratedMetadataProfiles ?? []);
    const filtered = all.filter((name) => !auto.has(name));
    return filtered.length > 0 ? filtered : all;
  }, [currentDatasets?.availableMetadataProfiles, currentDatasets?.autoGeneratedMetadataProfiles]);

  async function refreshCurrent() {
    const datasets = await getCurrentDatasets();
    setCurrentDatasets(datasets);
    return datasets;
  }

  useEffect(() => {
    refreshCurrent().catch((err) => {
      setError(err instanceof Error ? err.message : "Failed to load datasets");
    });
  }, []);

  useEffect(() => {
    return subscribeDatasetStateChanged(() => {
      refreshCurrent().catch(() => {
        // keep current snapshot if transient refresh fails
      });
    });
  }, []);

  useEffect(() => {
    setRenameMetadataProfileName(currentDatasets?.activeMetadataProfile ?? "Metadata");
  }, [currentDatasets?.activeMetadataProfile]);

  useEffect(() => {
    const active = currentDatasets?.activeMetadataProfile ?? "";
    if (!active || manualMetadataProfiles.includes(active)) return;
    const fallback = manualMetadataProfiles[0];
    if (!fallback) return;
    handleMetadataProfileChange(fallback).catch(() => {
      // keep current profile if switch fails
    });
  }, [currentDatasets?.activeMetadataProfile, manualMetadataProfiles]);

  useEffect(() => {
    if (availableKinds.length === 0) return;
    if (!availableKinds.includes(kind)) {
      setKind(availableKinds[0]);
    }
  }, [availableKinds, kind]);

  useEffect(() => {
    const suggestedLog2 = activeDataset?.suggestedIsLog2Transformed ?? true;

    getCurrentAnnotation(kind)
      .then((stored) => {
        setResult(stored);
        setIsLog2Transformed(stored.isLog2Transformed);
        if (stored.filter) {
          setFilterConfig(stored.filter);
        }
      })
      .catch(() => {
        setResult(null);
        setIsLog2Transformed(suggestedLog2);
      });
  }, [
    kind,
    activeDataset?.filename,
    activeDataset?.suggestedIsLog2Transformed,
    currentDatasets?.activeMetadataProfile,
  ]);

  useEffect(() => {
    getCurrentAnnotation("phosprot")
      .then((stored) => setPhosprotResult(stored))
      .catch(() => {
        setPhosprotResult(null);
      });
  }, [currentDatasets?.phosprot?.filename, currentDatasets?.activeMetadataProfile]);

  useEffect(() => {
    getUploadedAnnotationMetadata(kind)
      .then((metadata) => setUploadedMetadata(metadata))
      .catch(() => {
        setUploadedMetadata(null);
      });
  }, [kind, currentDatasets?.activeMetadataProfile]);

  useEffect(() => {
    setMetadataFile(null);
  }, [kind, currentDatasets?.activeMetadataProfile]);

  function addCondition() {
    setConditions((prev) => [
      ...prev,
      { id: Date.now(), name: "", columns: [] },
    ]);
  }

  function removeCondition(id: number) {
    setConditions((prev) => prev.filter((condition) => condition.id !== id));
  }

  function updateConditionName(id: number, name: string) {
    setConditions((prev) =>
      prev.map((condition) =>
        condition.id === id ? { ...condition, name } : condition
      )
    );
  }

  function updateConditionColumns(id: number, columns: string[]) {
    setConditions((prev) =>
      prev.map((condition) =>
        condition.id === id ? { ...condition, columns } : condition
      )
    );
  }

  const requestConditions = useMemo<ConditionAssignment[]>(() => {
    return conditions
      .map((condition) => ({
        name: condition.name.trim(),
        columns: condition.columns,
      }))
      .filter((condition) => condition.name.length > 0 && condition.columns.length > 0);
  }, [conditions]);

  async function handleGenerate() {
    if (!activeDataset) {
      setError(`No ${kind} dataset loaded. Upload data first.`);
      return;
    }

    try {
      setLoading(true);
      setError(null);

      const generated = await generateAnnotation({
        kind,
        conditions: requestConditions,
        isLog2Transformed,
        filter: filterConfig,
      });

      setResult(generated);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate annotation");
    } finally {
      setLoading(false);
    }
  }

  async function handleMetadataUpload() {
    if (!activeDataset) {
      setError(`No ${kind} dataset loaded. Upload data first.`);
      return;
    }
    if (!metadataFile) {
      setError("Please choose a metadata file first.");
      return;
    }

    try {
      setUploadingMetadata(true);
      setError(null);
      const uploaded = await uploadAnnotationMetadata(metadataFile, kind);
      setUploadedMetadata(uploaded);
      await refreshCurrent();
      setMetadataFile(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to upload metadata");
    } finally {
      setUploadingMetadata(false);
    }
  }

  async function handleAggregatePhosprot() {
    try {
      setPhosprotBusy(true);
      setError(null);
      const generated = await aggregatePhosprot(phosprotMode);
      setPhosprotResult(generated);
      await refreshCurrent();
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "Failed to aggregate phosphoprotein data"
      );
    } finally {
      setPhosprotBusy(false);
    }
  }

  async function handleCreateMetadataProfile() {
    const name = newMetadataProfileName.trim();
    if (!name) {
      setError("Please enter a metadata profile name.");
      return;
    }
    try {
      setMetadataProfileBusy(true);
      setError(null);
      await createMetadataProfile(name);
      await refreshCurrent();
      setNewMetadataProfileName("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create metadata profile");
    } finally {
      setMetadataProfileBusy(false);
    }
  }

  async function handleMetadataProfileChange(nextProfile: string) {
    const name = nextProfile.trim();
    if (!name) return;
    try {
      setMetadataProfileBusy(true);
      setError(null);
      await setActiveMetadataProfile(name);
      await refreshCurrent();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to switch metadata profile");
    } finally {
      setMetadataProfileBusy(false);
    }
  }

  async function handleRenameMetadataProfile() {
    const oldName = (currentDatasets?.activeMetadataProfile ?? "").trim();
    const newName = renameMetadataProfileName.trim();
    if (!oldName) {
      setError("No selected metadata profile.");
      return;
    }
    if (!newName) {
      setError("Please enter a new metadata profile name.");
      return;
    }
    try {
      setMetadataProfileBusy(true);
      setError(null);
      await renameMetadataProfile(oldName, newName);
      await refreshCurrent();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to rename metadata profile");
    } finally {
      setMetadataProfileBusy(false);
    }
  }

  const canAggregatePhosprot =
    kind === "phospho" &&
    result !== null &&
    result.metadataSource === "uploaded" &&
    uploadedMetadata !== null;

  return (
    <div className="space-y-6">
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 className="text-lg font-semibold text-slate-900">Data Annotation</h2>

        <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4">
          <div className="text-sm font-medium text-slate-700">Metadata Profiles</div>
          <p className="mt-1 text-sm text-slate-600">
            Manage selected metadata profile for this dataset package.
          </p>
          <div className="mt-3 grid gap-3 lg:grid-cols-3">
            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700">Selected metadata</label>
              <select
                value={currentDatasets?.activeMetadataProfile ?? "Metadata"}
                onChange={(event) => handleMetadataProfileChange(event.target.value)}
                disabled={metadataProfileBusy}
                className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900 disabled:cursor-not-allowed disabled:bg-slate-100"
              >
                {manualMetadataProfiles.map((name) => (
                  <option key={name} value={name}>
                    {name}
                  </option>
                ))}
              </select>
            </div>
            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700">New metadata profile</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={newMetadataProfileName}
                  onChange={(event) => setNewMetadataProfileName(event.target.value)}
                  placeholder="Metadata_2"
                  className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900"
                />
                <button
                  type="button"
                  onClick={handleCreateMetadataProfile}
                  disabled={metadataProfileBusy}
                  className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700 transition hover:bg-slate-100 disabled:opacity-50"
                >
                  Create
                </button>
              </div>
            </div>
            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700">Rename selected metadata</label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={renameMetadataProfileName}
                  onChange={(event) => setRenameMetadataProfileName(event.target.value)}
                  className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900"
                />
                <button
                  type="button"
                  onClick={handleRenameMetadataProfile}
                  disabled={metadataProfileBusy}
                  className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700 transition hover:bg-slate-100 disabled:opacity-50"
                >
                  Rename
                </button>
              </div>
            </div>
          </div>
        </div>

        <div className="mt-5 grid gap-4 lg:grid-cols-2">
          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Dataset level
            </label>
            <select
              value={kindOptions.length === 0 ? "" : kind}
              onChange={(e) => setKind(e.target.value as MetadataAnnotationKind)}
              disabled={kindOptions.length === 0}
              className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900 disabled:cursor-not-allowed disabled:bg-slate-100"
            >
              {kindOptions.length === 0 ? (
                <option value="">No dataset available</option>
              ) : (
                kindOptions.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))
              )}
            </select>
          </div>

          <div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm">
            <div className="font-medium text-slate-700">Current dataset</div>
            {activeDataset ? (
              <div className="mt-2 space-y-1 text-slate-600">
                <div className="truncate" title={activeDataset.filename}>
                  {activeDataset.filename}
                </div>
                <div>
                  {activeDataset.rows} rows, {activeDataset.columns} columns
                </div>
              </div>
            ) : (
              <div className="mt-2 text-slate-500">No dataset loaded.</div>
            )}
          </div>
        </div>

        <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">
          <label className="inline-flex items-center gap-2 text-sm text-slate-700">
            <input
              type="checkbox"
              checked={isLog2Transformed}
              onChange={(e) => setIsLog2Transformed(e.target.checked)}
            />
            Dataset is already log2 transformed
          </label>
        </div>

        {kindOptions.length === 0 ? (
          <div className="mt-4 rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-800">
            Upload a protein or phospho dataset in the Data tab before uploading metadata.
          </div>
        ) : null}

        <div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4">
          <div className="text-sm font-medium text-slate-700">Uploaded Metadata (Optional)</div>
          <p className="mt-1 text-sm text-slate-600">
            If a metadata file is uploaded for this level, it overrides UI condition mapping during annotation generation.
          </p>
          <div className="mt-3 grid gap-3 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
            <div>
              <label className="mb-2 block text-sm font-medium text-slate-700">Metadata file</label>
              <input
                key={`annotation-metadata-${kind}`}
                type="file"
                accept=".csv,.tsv,.txt,.xlsx,.parquet"
                onChange={(e) => setMetadataFile(e.target.files?.[0] ?? null)}
                disabled={!activeDataset}
                className="block w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm disabled:cursor-not-allowed disabled:bg-slate-100"
              />
            </div>
            <button
              type="button"
              onClick={handleMetadataUpload}
              disabled={!activeDataset || !metadataFile || uploadingMetadata}
              className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {uploadingMetadata ? "Uploading..." : "Upload Metadata"}
            </button>
          </div>

          {uploadedMetadata ? (
            <div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">
              Using uploaded metadata file: {uploadedMetadata.filename} ({uploadedMetadata.rows} rows) in profile{" "}
              <span className="font-medium">{uploadedMetadata.profileName}</span>
            </div>
          ) : (
            <div className="mt-3 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">
              No uploaded metadata for this dataset level.
            </div>
          )}
        </div>

      </section>

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h3 className="text-lg font-semibold text-slate-900">Condition Mapping</h3>

        <div className="mt-4 space-y-4">
          {conditions.map((condition) => (
            <div key={condition.id} className="rounded-xl border border-slate-200 p-4">
              <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(0,2fr)_auto]">
                <div>
                  <label className="mb-2 block text-sm font-medium text-slate-700">
                    Condition name
                  </label>
                  <input
                    type="text"
                    value={condition.name}
                    onChange={(e) => updateConditionName(condition.id, e.target.value)}
                    placeholder="Control"
                    className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-900"
                  />
                </div>

                <div>
                  <label className="mb-2 block text-sm font-medium text-slate-700">
                    Sample columns
                  </label>
                  <div className="overflow-x-auto rounded-xl border border-slate-300">
                    <select
                      multiple
                      value={condition.columns}
                      size={Math.max(4, Math.min(10, availableColumns.length || 4))}
                      onChange={(e) =>
                        updateConditionColumns(
                          condition.id,
                          Array.from(e.target.selectedOptions).map((option) => option.value)
                        )
                      }
                      className="min-w-full w-max border-0 px-3 py-2 text-sm outline-none"
                    >
                      {availableColumns.map((column) => (
                        <option key={column} value={column} className="whitespace-nowrap">
                          {column}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>

                <div className="self-end">
                  <button
                    type="button"
                    onClick={() => removeCondition(condition.id)}
                    className="rounded-xl border border-red-300 bg-white px-3 py-2 text-sm text-red-700 transition hover:bg-red-50"
                  >
                    Remove
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-4">
          <button
            type="button"
            onClick={addCondition}
            className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700 transition hover:bg-slate-50"
          >
            Add condition
          </button>
        </div>
      </section>

      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h3 className="text-lg font-semibold text-slate-900">Filter Settings</h3>
        <div className="mt-4 grid gap-4 lg:grid-cols-2">
          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Keep rows with at least N values
            </label>
            <input
              type="text"
              lang="en-US"
              inputMode="decimal"
              value={String(filterConfig.minPresent)}
              onChange={(e) =>
                setFilterConfig((prev) => ({
                  ...prev,
                  minPresent: Number(e.target.value.replace(",", ".")) || 0,
                }))
              }
              className="w-full rounded-xl border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-900"
            />
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Filter mode
            </label>
            <select
              value={filterConfig.mode}
              onChange={(e) =>
                setFilterConfig((prev) => ({
                  ...prev,
                  mode: e.target.value as AnnotationFilterConfig["mode"],
                }))
              }
              className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900"
            >
              <option value="per_group">Per group</option>
              <option value="in_at_least_one_group">In at least one group</option>
            </select>
          </div>
        </div>

        <div className="mt-5">
          <button
            type="button"
            onClick={handleGenerate}
            disabled={!activeDataset || loading}
            className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {loading ? "Generating..." : "Generate Annotation"}
          </button>
        </div>

        {error && (
          <div className="mt-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
            {error}
          </div>
        )}
      </section>

      {result ? (
        <>
          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h3 className="text-lg font-semibold text-slate-900">Result Summary</h3>
            <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
              <SummaryCard label="Source Rows" value={String(result.sourceRows)} />
              <SummaryCard label="Metadata Rows" value={String(result.metadataRows)} />
              <SummaryCard label="Conditions" value={String(result.conditionCount)} />
              <SummaryCard label="Filtered Rows" value={String(result.filteredRows)} />
              <SummaryCard label="Metadata Source" value={result.metadataSource} />
            </div>

            {result.warnings.length > 0 && (
              <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
                {result.warnings.join(" ")}
              </div>
            )}
          </section>

          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h3 className="text-lg font-semibold text-slate-900">Metadata Preview</h3>
            <div className="mt-4">
              <PreviewTable
                title="metadata_preview"
                rows={result.metadataPreview}
                emptyText="No metadata rows available."
              />
            </div>
          </section>

          <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
            <h3 className="text-lg font-semibold text-slate-900">Filtered Data Preview</h3>
            <div className="mt-4">
              <PreviewTable
                title="filtered_data_preview"
                rows={result.filteredPreview}
                emptyText="No filtered rows available."
              />
            </div>
          </section>

          {kind === "phospho" ? (
            <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
              <h3 className="text-lg font-semibold text-slate-900">
                Aggregate to Phosphoprotein
              </h3>

              {canAggregatePhosprot ? (
                <>
                  <p className="mt-2 text-sm text-slate-600">
                    Aggregate the current uploaded and annotated phosphosite dataset to
                    phosphoprotein level.
                  </p>
                  <div className="mt-4 grid gap-3 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
                    <div>
                      <label className="mb-2 block text-sm font-medium text-slate-700">
                        Aggregation mode
                      </label>
                      <select
                        value={phosprotMode}
                        onChange={(e) =>
                          setPhosprotMode(e.target.value as PhosprotAggregationMode)
                        }
                        className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900"
                      >
                        <option value="sum_mean_impute">sum_mean_impute</option>
                        <option value="sum_propagate_na">sum_propagate_na</option>
                        <option value="sum_ignore_na">sum_ignore_na</option>
                        <option value="mean">mean</option>
                      </select>
                    </div>
                    <button
                      type="button"
                      onClick={handleAggregatePhosprot}
                      disabled={!currentDatasets?.phospho || phosprotBusy}
                      className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      {phosprotBusy ? "Aggregating..." : "Aggregate to Phosphoprotein"}
                    </button>
                  </div>
                </>
              ) : (
                <div className="mt-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600">
                  Upload phospho metadata and generate phospho annotation first to enable
                  aggregation.
                </div>
              )}

              <div className="mt-3 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600">
                {currentDatasets?.phosprot ? (
                  <>
                    Current phosphoprotein dataset: {currentDatasets.phosprot.filename} (
                    {currentDatasets.phosprot.rows} rows)
                  </>
                ) : (
                  "No phosphoprotein dataset loaded yet."
                )}
              </div>

              {phosprotResult ? (
                <div className="mt-3 space-y-3">
                  <div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">
                    Phosphoprotein annotation ready: {phosprotResult.filteredRows} filtered rows,{" "}
                    {phosprotResult.conditionCount} conditions.
                  </div>
                  <PreviewTable
                    title="phosprot_filtered_data_preview"
                    rows={phosprotResult.filteredPreview}
                    emptyText="No phosphoprotein filtered rows available."
                  />
                </div>
              ) : null}
            </section>
          ) : null}
        </>
      ) : (
        <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">
          No annotation result yet.
        </section>
      )}
    </div>
  );
}

function SummaryCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl border border-slate-200 bg-slate-50 px-4 py-3">
      <div className="text-xs font-medium uppercase tracking-wide text-slate-500">
        {label}
      </div>
      <div className="mt-1 text-sm font-semibold text-slate-900">{value}</div>
    </div>
  );
}

function PreviewTable({
  title,
  rows,
  emptyText,
}: {
  title: string;
  rows: Record<string, unknown>[];
  emptyText: string;
}) {
  const columns = useMemo(() => {
    const seen = new Set<string>();
    rows.forEach((row) => {
      Object.keys(row).forEach((key) => seen.add(key));
    });
    return Array.from(seen);
  }, [rows]);

  if (rows.length === 0 || columns.length === 0) {
    return (
      <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-6 text-sm text-slate-500">
        {emptyText}
      </div>
    );
  }

  return (
    <div className="space-y-3">
      <a
        href={`data:text/csv;charset=utf-8,${encodeURIComponent(rowsToCsv(rows, columns))}`}
        download={`${title}.csv`}
        className="inline-flex rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700 transition hover:bg-slate-50"
      >
        Download CSV
      </a>
      <div className="max-h-[28rem] overflow-auto rounded-xl border border-slate-200">
        <table className="min-w-full table-fixed border-collapse text-sm">
          <thead className="bg-slate-50">
            <tr>
              {columns.map((column) => (
                <th
                  key={column}
                  className="border-b border-slate-200 px-3 py-2 text-left font-medium text-slate-700"
                >
                  {column}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, rowIndex) => (
              <tr key={rowIndex} className="odd:bg-white even:bg-slate-50/50">
                {columns.map((column) => {
                  const value = row[column];
                  const text = value == null ? "" : String(value);
                  return (
                    <td
                      key={`${rowIndex}-${column}`}
                      className="border-b border-slate-100 px-3 py-2 text-slate-600"
                      title={text}
                    >
                      <div className="max-w-[28ch] overflow-hidden text-ellipsis whitespace-nowrap">
                        {text}
                      </div>
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function rowsToCsv(rows: Record<string, unknown>[], columns: string[]): string {
  const escape = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`;
  const lines = [
    columns.join(","),
    ...rows.map((row) => columns.map((column) => escape(row[column])).join(",")),
  ];
  return lines.join("\n");
}
