import { useCallback, useEffect, useMemo, useState } from "react";
import {
  createDatasetPackage,
  getCurrentDatasets,
  renameDatasetPackage,
  savePeptidePath,
  setActiveDatasetPackage,
  uploadPeptideFile,
  uploadDataset,
} from "../../lib/api";
import { IS_VIEWER_MODE } from "../../lib/appMode";
import { subscribeDatasetStateChanged } from "../../lib/datasetEvents";
import type {
  CurrentDatasetsResponse,
  DatasetKind,
  DatasetPreviewResponse,
} from "../../lib/types";
import CurrentDatasetsPanel from "./CurrentDatasetsPanel";
import DatasetPreview from "./DatasetPreview";
import UploadForm from "./UploadForm";

type UploadPageProps = {
  onDatasetUploaded?: (dataset: DatasetPreviewResponse | null) => void;
  readOnly?: boolean;
};

type LocalFile = File & {
  path?: string;
};

function resolveSelectedPeptidePath(file: File, inputValue: string): string | null {
  const localPath = (file as LocalFile).path?.trim();
  if (localPath) {
    return localPath;
  }

  const raw = inputValue.trim();
  if (raw && !raw.toLowerCase().includes("fakepath")) {
    return raw;
  }

  return null;
}

export default function UploadPage({ onDatasetUploaded, readOnly = false }: UploadPageProps) {
  const [kind, setKind] = useState<DatasetKind>("protein");
  const [current, setCurrent] = useState<CurrentDatasetsResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [viewerRefreshAttempts, setViewerRefreshAttempts] = useState(0);
  const [packageBusy, setPackageBusy] = useState(false);
  const [newPackageName, setNewPackageName] = useState("");
  const [renamePackageName, setRenamePackageName] = useState("");

  const refreshCurrentDatasets = useCallback(async () => {
    const data = await getCurrentDatasets();
    setCurrent(data);
    return data;
  }, []);

  useEffect(() => {
    refreshCurrentDatasets().catch((err) => {
      // Do not show a blocking error on passive initial load.
      setCurrent({
        activePackage: "Data",
        availablePackages: ["Data"],
        activeMetadataProfile: "Metadata",
        availableMetadataProfiles: ["Metadata"],
        autoGeneratedMetadataProfiles: [],
        protein: null,
        phospho: null,
        phosprot: null,
        peptide: null,
      });
      console.warn(err);
    });
  }, [refreshCurrentDatasets]);

  useEffect(() => {
    return subscribeDatasetStateChanged(() => {
      refreshCurrentDatasets().catch(() => {
        // keep current state if transient refresh fails
      });
    });
  }, [refreshCurrentDatasets]);

  useEffect(() => {
    setRenamePackageName(current?.activePackage ?? "");
  }, [current?.activePackage]);

  const displayedDataset = useMemo(() => {
    if (!current || kind === "peptide") return null;
    return current[kind];
  }, [current, kind]);

  useEffect(() => {
    onDatasetUploaded?.(displayedDataset);
  }, [displayedDataset, onDatasetUploaded]);

  useEffect(() => {
    if (!readOnly || !IS_VIEWER_MODE) return;

    const hasAnyDataset =
      Boolean(current?.protein) ||
      Boolean(current?.phospho) ||
      Boolean(current?.phosprot) ||
      Boolean(current?.peptide);
    if (hasAnyDataset) return;
    if (viewerRefreshAttempts >= 20) return;

    const timer = window.setTimeout(() => {
      setViewerRefreshAttempts((value) => value + 1);
      refreshCurrentDatasets().catch(() => {
        // keep current fallback state if backend is still booting
      });
    }, 700);
    return () => window.clearTimeout(timer);
  }, [current, readOnly, viewerRefreshAttempts, refreshCurrentDatasets]);

  async function handleFileSubmit(
    file: File,
    uploadKind: "protein" | "phospho" | "phosprot"
  ) {
    try {
      setLoading(true);
      setError(null);

      await uploadDataset(file, uploadKind);
      const updated = await refreshCurrentDatasets();

      onDatasetUploaded?.(updated[uploadKind]);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Upload failed");
    } finally {
      setLoading(false);
    }
  }

  async function handlePeptideSubmit(file: File, inputValue: string) {
    try {
      setLoading(true);
      setError(null);

      const resolvedPath = resolveSelectedPeptidePath(file, inputValue);
      if (resolvedPath) {
        await savePeptidePath(resolvedPath);
      } else {
        await uploadPeptideFile(file);
      }
      await refreshCurrentDatasets();

      onDatasetUploaded?.(null);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Saving path failed");
    } finally {
      setLoading(false);
    }
  }

  async function handleActivePackageChange(nextPackage: string) {
    if (!nextPackage.trim()) return;
    try {
      setPackageBusy(true);
      setError(null);
      await setActiveDatasetPackage(nextPackage);
      await refreshCurrentDatasets();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to switch dataset package");
    } finally {
      setPackageBusy(false);
    }
  }

  async function handleCreatePackage() {
    const name = newPackageName.trim();
    if (!name) {
      setError("Please enter a dataset name.");
      return;
    }
    try {
      setPackageBusy(true);
      setError(null);
      await createDatasetPackage(name);
      await refreshCurrentDatasets();
      setNewPackageName("");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create dataset package");
    } finally {
      setPackageBusy(false);
    }
  }

  async function handleRenameActivePackage() {
    const currentName = current?.activePackage?.trim() || "";
    const nextName = renamePackageName.trim();
    if (!currentName) {
      setError("No active dataset package selected.");
      return;
    }
    if (!nextName) {
      setError("Please enter a new dataset name.");
      return;
    }
    try {
      setPackageBusy(true);
      setError(null);
      await renameDatasetPackage(currentName, nextName);
      await refreshCurrentDatasets();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to rename dataset package");
    } finally {
      setPackageBusy(false);
    }
  }

  return (
    <div className="space-y-6">
      {readOnly ? (
        <section className="space-y-3 rounded-2xl border border-sky-200 bg-sky-50 px-4 py-3">
          <div className="text-sm text-sky-800">
            Viewer mode is read-only. Data is loaded from <code>viewer_config.json</code>.
          </div>
          <div>
            <label className="mb-2 block text-sm font-medium text-slate-700">
              Dataset level preview
            </label>
            <select
              value={kind}
              onChange={(e) => setKind(e.target.value as DatasetKind)}
              className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900 lg:max-w-sm"
            >
              <option value="protein">Protein</option>
              <option value="phospho">Phospho</option>
              <option value="phosprot">Phosphoprotein</option>
              <option value="peptide">Peptide</option>
            </select>
          </div>
        </section>
      ) : (
        <>
          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 className="text-lg font-semibold text-slate-900">Dataset Manager</h2>
            <p className="mt-1 text-sm text-slate-600">
              Create, rename, and select dataset packages. Upload and annotation actions apply to the selected package.
            </p>

            <div className="mt-4 grid gap-4 lg:grid-cols-3">
              <div>
                <label className="mb-2 block text-sm font-medium text-slate-700">Selected dataset</label>
                <select
                  value={current?.activePackage ?? "Data"}
                  onChange={(event) => handleActivePackageChange(event.target.value)}
                  disabled={packageBusy}
                  className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900 disabled:cursor-not-allowed disabled:bg-slate-100"
                >
                  {(current?.availablePackages ?? ["Data"]).map((name) => (
                    <option key={name} value={name}>
                      {name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="mb-2 block text-sm font-medium text-slate-700">New dataset</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={newPackageName}
                    onChange={(event) => setNewPackageName(event.target.value)}
                    placeholder="Dataset_2"
                    className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900"
                  />
                  <button
                    type="button"
                    onClick={handleCreatePackage}
                    disabled={packageBusy}
                    className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700 transition hover:bg-slate-100 disabled:opacity-50"
                  >
                    Create
                  </button>
                </div>
              </div>

              <div>
                <label className="mb-2 block text-sm font-medium text-slate-700">Rename selected dataset</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={renamePackageName}
                    onChange={(event) => setRenamePackageName(event.target.value)}
                    placeholder="Data"
                    className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm outline-none focus:border-slate-900"
                  />
                  <button
                    type="button"
                    onClick={handleRenameActivePackage}
                    disabled={packageBusy}
                    className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm text-slate-700 transition hover:bg-slate-100 disabled:opacity-50"
                  >
                    Rename
                  </button>
                </div>
              </div>
            </div>
          </section>

          <UploadForm
            kind={kind}
            loading={loading}
            onKindChange={setKind}
            onFileSubmit={handleFileSubmit}
            onPeptideSubmit={handlePeptideSubmit}
          />
        </>
      )}

      <CurrentDatasetsPanel current={current} />

      {error && (
        <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </div>
      )}

      {kind !== "peptide" && displayedDataset ? (
        <DatasetPreview dataset={displayedDataset} />
      ) : kind === "peptide" ? (
        <div className="rounded-2xl border border-slate-200 bg-white p-6">
          <h2 className="text-lg font-semibold text-slate-900">Preview</h2>
          <p className="mt-2 text-sm text-slate-500">
            Peptide datasets store only the selected local file path. No preview is shown.
          </p>
        </div>
      ) : (
        <div className="rounded-2xl border border-slate-200 bg-white p-6">
          <h2 className="text-lg font-semibold text-slate-900">Preview</h2>
          <p className="mt-2 text-sm text-slate-500">
            No {kind} dataset uploaded yet.
          </p>
        </div>
      )}
    </div>
  );
}
