import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  getCurrentDatasets,
  setActiveDatasetPackage,
  setActiveMetadataProfile,
} from "./api";
import type { AnnotationKind, CurrentDatasetsResponse } from "./types";
import { IS_VIEWER_MODE } from "./appMode";
import { subscribeDatasetStateChanged } from "./datasetEvents";

export type AnnotationKindOption = {
  value: AnnotationKind;
  label: string;
};

export function availableAnnotationKinds(
  datasets: CurrentDatasetsResponse | null
): AnnotationKind[] {
  const kinds: AnnotationKind[] = [];
  if (datasets?.protein) kinds.push("protein");
  if (datasets?.phospho) kinds.push("phospho");
  if (datasets?.phosprot) kinds.push("phosprot");
  return kinds;
}

export function annotationKindOptions(
  kinds: AnnotationKind[]
): AnnotationKindOption[] {
  return kinds.map((kind) => ({
    value: kind,
    label:
      kind === "protein"
        ? "Protein"
        : kind === "phospho"
          ? "Phospho"
          : "Phosphoprotein",
  }));
}

export function useCurrentDatasetsSnapshot() {
  const [datasets, setDatasets] = useState<CurrentDatasetsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const viewerRetryCountRef = useRef(0);

  const refresh = useCallback(async (silent = false) => {
    try {
      if (!silent) {
        setLoading(true);
      }
      setError(null);
      const current = await getCurrentDatasets();
      setDatasets(current);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load current datasets");
      setDatasets(null);
    } finally {
      if (!silent) {
        setLoading(false);
      }
    }
  }, []);

  useEffect(() => {
    refresh();
  }, [refresh]);

  useEffect(() => {
    return subscribeDatasetStateChanged(() => {
      refresh(true).catch(() => {
        // keep previous snapshot if refresh fails transiently
      });
    });
  }, [refresh]);

  useEffect(() => {
    const hasAnyDataset =
      Boolean(datasets?.protein) ||
      Boolean(datasets?.phospho) ||
      Boolean(datasets?.phosprot) ||
      Boolean(datasets?.peptide);

    if (!IS_VIEWER_MODE) {
      if (datasets !== null) return;
      const timer = window.setTimeout(() => {
        refresh(true).catch(() => {
          // next retry is scheduled by this effect if datasets stays null
        });
      }, 2000);
      return () => window.clearTimeout(timer);
    }

    if (hasAnyDataset) return;
    if (viewerRetryCountRef.current >= 20) return;

    const timer = window.setTimeout(() => {
      viewerRetryCountRef.current += 1;
      refresh(true).catch(() => {
        // continue retrying for a short bootstrap window in viewer mode
      });
    }, 500);
    return () => window.clearTimeout(timer);
  }, [datasets, refresh]);

  const kinds = useMemo(() => availableAnnotationKinds(datasets), [datasets]);
  const options = useMemo(() => annotationKindOptions(kinds), [kinds]);
  const availablePackages = useMemo(
    () => (datasets?.availablePackages ?? []).filter((value) => value.trim().length > 0),
    [datasets]
  );
  const activePackage = datasets?.activePackage ?? availablePackages[0] ?? "Data";
  const availableMetadataProfiles = useMemo(
    () => (datasets?.availableMetadataProfiles ?? []).filter((value) => value.trim().length > 0),
    [datasets]
  );
  const autoGeneratedMetadataProfiles = useMemo(
    () => (datasets?.autoGeneratedMetadataProfiles ?? []).filter((value) => value.trim().length > 0),
    [datasets]
  );
  const activeMetadataProfile =
    datasets?.activeMetadataProfile ?? availableMetadataProfiles[0] ?? "Metadata";

  const setActivePackage = useCallback(async (packageName: string) => {
    const next = packageName.trim();
    if (!next) return;
    const updated = await setActiveDatasetPackage(next);
    setDatasets(updated);
  }, []);
  const setMetadataProfile = useCallback(async (profileName: string) => {
    const next = profileName.trim();
    if (!next) return;
    const updated = await setActiveMetadataProfile(next);
    setDatasets(updated);
  }, []);

  return {
    datasets,
    loading,
    error,
    refresh,
    activePackage,
    availablePackages,
    setActivePackage,
    activeMetadataProfile,
    availableMetadataProfiles,
    autoGeneratedMetadataProfiles,
    setMetadataProfile,
    availableKinds: kinds,
    kindOptions: options,
  };
}
